language: python
python: 2.7
env:
  matrix:
  - TOXENV=py27
  - TOXENV=flake8
matrix:
  allow_failures:
  - env: TOXENV=flake8
install:
- pip install -U tox
script: tox
deploy:
  provider: pypi
  user: scrapinghub
  distributions: sdist bdist_wheel
  password:
    secure: bG1ycgBJrVfgBsHAwaWScL2V1x52/aZy2znE2kFzFfYq95HS51mu1GO2PKwpATJyMCs/xUIKGhiBtoo8LzNmNU2kPgarQFwzpLkx2ninOm+3uAwuIfGGWsonBW/h854n+cNwppJOlfEOxvMVerVVpdV4EFeJfEkVYascwOBbnqo=
  on:
    branch: master
    repo: scrapinghub/scrapy-streamitem
    condition: $TOXENV == py27
