language: python
python: 2.7
env:
  matrix:
  - TOXENV=py27
  - TOXENV=flake8
matrix:
  allow_failures:
  - env: TOXENV=flake8
install:
- pip install -U tox
script: tox
deploy:
  provider: pypi
  user: gatufo
  distributions: sdist bdist_wheel
  password:
    secure: bfz2enDE6Ukeq/WZx0Om04qKidMx2xKF168Me8RlxZnFMSKZsDODo2nbn9mizYYa7/NUviuXknjW+RVhZEPp4K9kHvbNXFOfwoF2yruohro04Y8se871o8lmpiZgiN4Y0wXr0XVrDDK/KoQZJfz7/ZFPgMKAmwEWHPp2bA96zoA=
  on:
    branch: master
    repo: scrapinghub/scrapy-streamitem
    condition: $TOXENV == py27
