language: python
python: 2.7
env:
  matrix:
  - TOXENV=py27
  - TOXENV=flake8
matrix:
  allow_failures:
  - env: TOXENV=flake8
install:
- pip install -U tox
script: tox
deploy:
  provider: pypi
  user: scrapinghub
  distributions: sdist bdist_wheel
  password:
    secure: Ttqyx+X/WKjXiZ3AH8rG1Tbu0mRFufR0B8zJtsxVGtLYYyBnQCKLkkdfN464KTGuh9oHW0airwUOOf3Wlhjuuc705QN73kUsZ0g2VVqW2M0/9mRED1E64npDvXWQWYTahNAQNL9GltT6F/ARO1fFg34EK6+2ksHcZ7hVn/j8H3w=
  on:
    branch: master
    repo: scrapinghub/scrapy-streamitem
    condition: $TOXENV == py27
